from __future__ import annotations

DEFAULT_RISK_LEVEL_HIGH_THRESHOLD = 55
DEFAULT_RISK_LEVEL_MEDIUM_THRESHOLD = 75
DEFAULT_MAX_CONTEXT_CHARS = 4500
DEFAULT_CHUNK_SIZE = 900
DEFAULT_CHUNK_OVERLAP = 120
DEFAULT_ANALYSIS_ID_PREFIX = "agr"
